---
- name: Create directories
  file:
    state: directory
    path: "{{ item }}"
    mode: 0755
  with_items:
    - /opt/docker-compose-service
    - /var/log/docker-compose-service

- name: Uninstall docker from distribution
  apt:
    name: ["docker", "docker-engine", "docker.io"]
    state: absent

- name: Add official docker's apt key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add official docker's apt-repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_facts.distribution_release }} stable"
    state: present

- name: Install packages
  apt:
    name: ["docker-ce"]
    state: present

- name: install python docker module
  pip:
    name: docker

- name: Install docker-compose
  get_url:
    url: https://github.com/docker/compose/releases/latest/download/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: 0755


- name: Put compose unit file
  template:
    src: docker-compose-service@.service.j2
    dest: /etc/systemd/system/docker-compose-service@.service
    mode: 0755

- name: users joins to docker
  user:
    name: "{{item}}"
    create_home: yes
    shell: /bin/bash
    append: yes
    groups:
      - docker
  with_items: "{{ docker_users }}"

- name: Create networks
  docker_network:
    name: "{{item}}"
  with_items: "{{ docker_networks }}"